### PR TITLE
Google Pay and other improvements

### LINKED ISSUE #16: GoogleMerchantID is Missing ???
Hi @wgltony,
         How do i configure the GoogleMerchantID ?

Thanks & regards,
Hari

### PR DESCRIPTION
**Pull request by BradyShober**
With the release of RN 0.60 we can update to the latest version of the Braintree drop in which allows us to support Google Pay which fixes #16. I have also enabled the use of the vault manager through a configuration option and made improvements to Apple Pay handling that will detect if a user has cancelled payment from the Apple Pay screen. I tried to get autolinking support working but wasn't able to figure that out for iOS, if anyone has more experience with that and would like to get that working that would be great!

### CODE REVIEW

**Comment by BradyShober** [comment]
In reference to the linking issues on iOS, I had things working in RN version 0.58 but have updated to RN 0.60 and am able to use the package fine on Android with autolinking but on iOS have been getting TypeError: Cannot read property 'show' of undefined. I've not yet been able to determine why this is happening as I have tried manual linking instead of autolinking and am still having the issue.

**Comment by BradyShober** [comment]
The issue in my previous comment has been resolved, the PR should be good to go now

**Comment by adamfellon** [comment]
Hi @BradyShober Did you end up just using your branch for these changes?  I'm in the process of moving off RN `0.57.8` to `0.60.0` and saw your changes with the podspec etc was wondering if/why this didn't get merged.

Thanks!

**Comment by BradyShober** [comment]
@adamfellon I ended up doing some reorganization in my fork and made a new PR #25  after those changes which has been merged today

**Comment by adamfellon** [comment]
Ok, cool.  I got your fork to work this afternoon, but ran into a weird dependency issue...did you ever run into the 3D secure issues for android?

I had to add this braintree dependency to my project from this alternate project: https://github.com/bamlab/react-native-braintree-payments-drop-in/blob/master/android/build.gradle#L39

I'll try again with this package tomorrow with the merge.

Thanks!

**Comment by BradyShober** [comment]
@adamfellon I did not, but we were not using any 3D secure features in our application. Are you trying to use 3D secure? I may not have caught it if that was the case.

**Pull request closed without merging**
